### PR TITLE
Allow user maximize form full screen

### PR DESCRIPTION
**Pull request by chuongmep**
# Summary of the Pull Request

**What is this about:** 
This is a small update allow user can maximize form full screen, may be will useful if have a long string data or user need expand form to review.
**Description:** 
Before : 
image
After :
Revit_MkbkoOBqJW

## Quality Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Nice3point** [comment]
@chuongmep  Minimize button disabled?

**Comment by chuongmep** [comment]
@Nice3point yes, you want turn on it ?

**Comment by Nice3point** [comment]
@chuongmep  I think yes, otherwise why this button is needed)

**Comment by Nice3point** [comment]
@chuongmep  this is not exactly the behavior that should be) the window is not minimized, but reduced to the minimum size with a slight lag
изображение

**Comment by chuongmep** [comment]
Fixed, becuase still exist setting AutoScaleBaseSize  for form
https://user-images.githubusercontent.com/31106432/156343205-2d20c8b9-8f46-4366-88be-5f0cd4bd2e1e.mp4

**Comment by chuongmep** [comment]
@Nice3point, fixed, only need change some anchor of button.
MWwJY8qta9

**Comment by Nice3point** [comment]
@chuongmep not enough minimum size for other window types))
изображение

**Comment by chuongmep** [comment]
@Nice3point  Don't have any problem from me ? 
https://user-images.githubusercontent.com/31106432/156389759-442cee06-2084-4843-b397-b8433955ed21.mp4

**Comment by Nice3point** [comment]
@chuongmep try resize

**Comment by Nice3point** [comment]
@chuongmep I think we need to do the same for all these windows
изображение

**Comment by chuongmep** [comment]
No problem ! @Nice3point
https://user-images.githubusercontent.com/31106432/156390543-18aceba0-0a77-4906-9e33-9674a373f2d8.mp4

**Comment by chuongmep** [comment]
oh i see.Let me fix now, sorry for misunderstanding your point :D

**Comment by chuongmep** [comment]
@Nice3point fixed, include some other form.

https://user-images.githubusercontent.com/31106432/156392961-014d70e2-d932-40bf-a034-ef014681ffbf.mp4

**Comment by Nice3point** [comment]
@chuongmep awesome)

**Pull request merged**
