### PR TITLE
Modeless windows

### PR DESCRIPTION
**Pull request by NeVeSpl**
That required more changes than I expected, but the final effect is quite nice.  I hope that I have not broken any existing functionality.

### CODE REVIEW

**Comment by jeremytammik** [comment]
wow! this is the most exciting pull request ever. fraught with risk, of course. cool.

**Comment by jeremytammik** [comment]
i see one very apt comment:

			// TBD: For the Snoop.Data.ElementId object I need access to the current
			// document so I can retrieve the Element.  However, from the context of something
			// like a Parameter.AsElementId(), the Document is nowhere to be found.  So, hack
			// around it for now by letting original TestCmd set this value.  Its not local-enough
			// when browsing though, so it could be wrong if browsing doesn't stay within the 
			// original document! (jma - 05/03/05)

would it be easy to implement a warning message when the user (inadvertently) swaps to a different document?

easier than implementing the full solution?

**Comment by NeVeSpl** [comment]
I must admit I have not looked into CollectorExtElement and *Stream classes to check how they determine on which document they are working, but they definitely did not use  ``static public Autodesk.Revit.DB.Document m_activeDoc = null;`` which was below that comment. I will look into that deeper, but after first a few clicks switching documents does not seem to cause any problems...

**Comment by jeremytammik** [comment]
brilliant! Thank you very much for taking such a careful look!

**Pull request merged**
