### PR TITLE
Update settings.

### PR DESCRIPTION
**Pull request by Andrey-Bushman**
* Switch the target platform to .Net 4.6.
  * Replace Revit2017 NuGet package by Revit2018.1 Nuget package.

### CODE REVIEW

**Comment by jeremytammik** [comment]
hi andrey, thank you for your pull request! 

1. why do you require .net 4.6? this is not required by revit, is it? does the nuget package need this?

2. why do you add so many new revit api dll references? adwindows, macros, uimacros, IFC...? does the nuget package need this?

i prefer keeping RevitLookup as minimal as possible, for obvious reasons...

i like the idea of using the NuGET package per se, as long as there is a certainty that it is updated in a timely fashion.

i would prefer leaving the .net version as required by revit, and only reference the necessary revit api dlls, though.

can you fix this?

thank you!

**Comment by Andrey-Bushman** [comment]
hi jeremy,

> why do you require .net 4.6? this is not required by revit, is it? does the nuget package need this?

Because I read about .net 4.6 [here](https://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2018/ENU/Revit-API/files/GUID-FEF0ED40-8658-4C69-934D-7F83FB5D5B63-htm.html):

> Revit's binaries are built using .NET 4.5.2. **However, Revit uses the runtime from .NET 4.6.**

> why do you add so many new revit api dll references? adwindows, macros, uimacros, IFC...? does the nuget package need this?

These DLL files were added by NuGet packages. The `RevitAPI.dll` and `RevitAPIUI.dll` libraries are used by [Revit2018DevTools](https://github.com/Andrey-Bushman/RevitDevTools) -  this is one of my NuGet packages, it is used by [Revit2018AddInTemplateSet](https://github.com/Andrey-Bushman/Revit2018AddInTemplateSet) templates.

>  i prefer keeping RevitLookup as minimal as possible, for obvious reasons...

Additional references don't take a place, but it is convenient when they already added instead of requiring the programmer to add them each time manually. Creating a NuGet package for each DLL and then downloading each one separately is inconvenient and annoying to the developers. I asked some of them about it.

> i would prefer leaving the .net version as required by revit, and only reference the necessary revit api dlls, though.

No problem, you can reject my pull request. In the first quote, I explained the reason why I use .net 4.6. I prefer to use the version of .net that Revit uses in runtime.

**Comment by jeremytammik** [comment]
thank you very much for the explanation. you convinced me  :-)

**Comment by goldensamurai** [comment]
Hi guys,

I will start with probably the most used expression in the developer world: I am a beginner so buckle up. :) I'm a Revit and Navisworks user. I started working with DYNAMO, then I switched to Python and now I'm here.

I found your first youtube video: _"Revit2017AddInTemplateSet: #001. Download and install the templates."_[https://www.youtube.com/watch?v=SYm-yxQ9jFk&t=1s](url). And I tried all the possible ways I could, with my knowledge but it didn't work launching the configurator.

I started as you mentioned in the video with changing the CustomParameters.xml. I changed them manually(not sure that is the right way).
```
<?xml version="1.0" encoding="UTF-8"?>
-<Settings>
<!-- RevitAddInTemplateSet code sources. YOU DON'T NEED TO EDIT THESE SETTINGS IF YOU DIDN'T CHANGE PLACEMENT OF THESE DIRECTORIES.-->

-<CodeSources>
<!-- Each subfolder of this folder contains the code sources of the individual project template. -->
<ProjectTemplatesRootFolder>..\..\C# Project templates </ProjectTemplatesRootFolder>
<!-- Each subfolder of this folder contains the code sources of the individual item template. -->
<ItemTemplatesRootFolder>..\..\C# Item Templates </ItemTemplatesRootFolder>
</CodeSources>

<!-- Custom parameters which are to be updated in the vstemplate-file of code sources of each template before they will be builded and installed. YOU ARE TO EDIT THE VALUES OF 'VALUE' ATTRIBUTES. Set their values as you need. But you aren't to edit the values of 'Name' attributes! Also, don't delete the 'CustomParameter' xml-elements. -->
-<CustomParameters>
<CustomParameter Value="BUSHMAN" Name="$ClientId$"/>
<CustomParameter Value="ru.blogspot.revit-addins" Name="$VendorId$"/>
<CustomParameter Value="Bushman" Name="$CompanyName$"/>
<CustomParameter Value="Bushman" Name="$RootNamespace$"/>
<CustomParameter Value="https://revit-addins.blogspot.ru" Name="$WebPage$"/>
<CustomParameter Value="2017" Name="$AppYear$"/>
</CustomParameters>
</Settings>
```
Didn't work. So then I changed again manually the file as I saw it in the video:

2017-10-05_15h31_25

Didn't work.
I asked some C# developers but they need some time. I would appreciate a lot if you could explain me what am I doing wrong.

Kind regards,
Daniel

**Comment by jeremytammik** [comment]
@goldensamurai why are you asking questions about the Revit add-in template set in this repository, which is owned by RevitLookup? you are in the wrong place. please add your comment in the Revit add-in template set repository instead. Thank you.

**Pull request merged**
