### PR TITLE
Snoop rendering AssetProperty

### PR DESCRIPTION
**Pull request by chekalin-v**
Snoop rendering AssetProperty
Material->AppearanceAssetId->GetRenderingAssset

Snoop_Asset_1
Snoop_Asset_2
Snoop_Asset_3
Snoop_Asset_4

### CODE REVIEW

**Comment by chekalin-v** [comment]
Not sure why in the last screenshot properties were not visible

Snoop_Asset_4

**Comment by jeremytammik** [comment]
------ Rebuild All started: Project: RevitLookup, Configuration: Debug (For Release build of Revit) Any CPU ------
CSC : error CS2001: Source file 'C:\a\vs\RevitLookup\CS\Snoop\Data\AssetProperty.cs' could not be found.
CSC : error CS2001: Source file 'C:\a\vs\RevitLookup\CS\Snoop\Data\DoubleArray.cs' could not be found.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by jeremytammik** [comment]
did you submit AssetProperty.cs and DoubleArray.cs?

**Comment by chekalin-v** [comment]
Oops. See the new pull request

**Comment by jeremytammik** [comment]
great! thank you!

**Comment by jeremytammik** [comment]
https://thebuildingcoder.typepad.com/blog/2019/03/-architecture-edit-and-continue-snooping-appearance-assets.html#4

**Pull request merged**
