### PR TITLE
Fixed CI for Revit 2022 and non-dotnet-core project file

### PR DESCRIPTION
**Pull request by peterhirn**
Added 2022 configuration to solution
Replaced copy with xcopy in post-build step

Can't get rid of whitespace changes in `RevitLookup.csproj` lines 4-5 and 53-56.

Addendum: also fixed `RevitLookup.csproj.new`

### CODE REVIEW

**Comment by jeremytammik** [comment]
integrated in release 2022.0.0.2 https://github.com/jeremytammik/RevitLookup/releases/tag/2022.0.0.2

**Comment by jeremytammik** [comment]
There is still quite a bit of weirdness going on... I just had to reset thr DLL assembly references to Copy Local = false. I also had to set the configuration property to 2022. When I tried to set it to 'Debug for Release version of Revit', it failed to compile with an error saying 'OutputPath not set'.

**Comment by peterhirn** [comment]
Copy local was removed here: https://github.com/jeremytammik/RevitLookup/commit/6885ddab12cc716a1a68fe9143b3deb053e440b5

Having the Revit target version as configuration name in the solution - instead of Release/Debug - is confusing and a bad idea imho.

**Comment by jeremytammik** [comment]
Ah, well maybe I inadvertently added the copy local back again. Now i removed it once more. I fully agree about the config practice, I just don't know how to achieve that. maybe if you look at the solution and project files in 2022.0.0.3 you can see what went wrong?

**Comment by peterhirn** [comment]
The solution file in 2022.0.0.3 contains questionable entries:

    {05C77115-2277-4DFC-8F95-BE37E5F1130F}.2019|Any CPU.ActiveCfg = 2022|Any CPU
    {05C77115-2277-4DFC-8F95-BE37E5F1130F}.2019|Any CPU.Build.0 = 2022|Any CPU

2019 = 2022? Probably related to what is consider the "active" configuration in VS.

Please consider just upgrading to VS 2019 and using my solution and csproj files. ;)

**Comment by jeremytammik** [comment]
Yes, fully agree. Will do.

**Comment by jeremytammik** [comment]
done in release 2022.0.0.4. can you check whether it is better now? thank you!

**Comment by peterhirn** [comment]
Nice! Is the project now working for you in VS2019, debug builds etc.? I will submit a PR for the ci tomorrow.

**Comment by peterhirn** [comment]
I hard-coded the paths to the Revit 2022 install directory in the `csproj` file:

```
  <ItemGroup Condition="'$(CI)' != 'True'">
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2022\RevitAPI.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2022\RevitAPIUI.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(CI)' == 'True'">
    <Reference Include="RevitAPI">
      <HintPath>..\revit-api\RevitAPI.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\revit-api\RevitAPIUI.dll</HintPath>
    </Reference>
  </ItemGroup>
```

This now requires a `Condition` for the CI, which is why I started to talk about the Revit Assemblies/Nuget in the other PR.

**Comment by jeremytammik** [comment]
Yes, I confirm that it does indeed reference the Revit 2022 API assemblies. Thank you for that! I initiated an internal discussion about officially providing them on NuGet.,

**Comment by peterhirn** [comment]
Glad I can help. Having official Revit API packages on nuget.org would be fantastic.

**Pull request merged**
