### PR TITLE
Geometry visualization

### PR DESCRIPTION
**Pull request by Nice3point**
# Summary of the Pull Request

**What is this about:** 

Geometry visualization engine

**Description:** 

In Revit, geometry is at the core of every model. Whether you are dealing with simple shapes or intricate structures, having the ability to visualize geometric elements can significantly improve your workflow, analysis and understanding of the BIM.

Visualization available in the context menu for each object:

изображение

## Mesh visualization

The Mesh Visualization feature emphasizes the detailed structure of a mesh, providing insights into its geometric composition.
Meshes consist of vertices, forming a network that approximates the surface of a 3D object.
This feature enables to:

- Explore the intricate details of a mesh's structure.
- Understand the distribution and vertices organization.
- Analyze the mesh orientation faces through normal vectors.

изображение

| Setting       | Description                                                                                    |
|---------------|------------------------------------------------------------------------------------------------|
| Surface       | Shows the mesh surface                                                                         |
| Extrusion     | Adjusts the depth of the mesh surface extrusion to enhance the 3D appearance for small objects |
| Transparency  | Sets the mesh surface transparency                                                             |
| Mesh grid     | Shows the mesh grid lines, highlighting the individual faces and their connections.            |
| Normal vector | Shows the normal vectors of the mesh vertices                                                  |

## Face visualization

The Face Visualization feature focuses on rendering and inspecting individual faces of solid geometry.
Faces are planar or curved surfaces that define the boundaries of a solid.
This feature enables users to:

- Inspect the detailed structure of a face within the model.
- Visualize the orientation and normal vector of a face.

изображение

| Setting       | Description                                                                                    |
|---------------|------------------------------------------------------------------------------------------------|
| Surface       | Shows the face surface                                                                         |
| Extrusion     | Adjusts the depth of the face surface extrusion to enhance the 3D appearance for small objects |
| Transparency  | Sets the face surface transparency                                                             |
| Mesh grid     | Shows the mesh grid lines, highlighting the individual faces and their connections.            |
| Normal vector | Shows the face centroid normal vector                                                          |

## Solid visualization

The Solid Visualization feature provides a comprehensive view of the entire solid geometry within a model.
Solids are volumetric shapes that define the three-dimensional space occupied by objects.
This feature enables users to:

- Comprehend the full volume of the solids.
- Analyze the geometric boundaries and surfaces of solids.
- Inspect the internal and external structure of complex solid forms.

изображение

| Setting           | Description                                                                             |
|-------------------|-----------------------------------------------------------------------------------------|
| Faces             | Shows the solid faces                                                                   |
| Transparency      | Sets the face surface transparency                                                      |
| Edges             | Shows the solid edges                                                                   |
| Cage Surface      | Shows a cage around the solid, simplifying the representation of the solid's boundaries |
| Cage Size         | Adjusts the size of the cage                                                            |
| Cage Transparency | Sets the cage surface transparency                                                      |

The **wireframe** display mode is best suited for this type of geometry. 
However, if you need to completely isolate the Revit geometry from the visualised geometry, temporarily **hide** the element being explored.
To analyze internal structure, use section box, hide the element and crop it.

## Curve visualization

The Curve Visualization feature highlights curves within the geometry, including lines, arcs, splines, and others.
Curves define the paths and shapes in a model.
This feature enables users to:

- Visualize the detailed curve structure.
- Visualize the curve segments directions.
- Analyze the curvature and continuity of lines, arcs, and splines.

изображение

| Setting      | Description                                                               |
|--------------|---------------------------------------------------------------------------|
| Surface      | Shows the surface along the curve path                                    |
| Diameter     | Adjusts the diameter of the curve visualization, enhancing its visibility |
| Transparency | Adjusts the transparency level of the curve surface                       |
| Polyline     | Shows the polyline approximation of the curve                             |
| Direction    | Shows the curve segments directions                                       |

Visualisation is only available for bound or cyclic curves

## Edge visualization

The Edge Visualization feature focuses on the edges of geometry, which are the lines where two faces meet.
This feature enables users to:

- Analyze the connectivity and topology of edges.
- Visualize the edge segments directions.

изображение

| Setting      | Description                                                              |
|--------------|--------------------------------------------------------------------------|
| Surface      | Shows the surface along the edge path                                    |
| Diameter     | Adjusts the diameter of the edge visualization, enhancing its visibility |
| Transparency | Adjusts the transparency level of the edge surface                       |
| Polyline     | Shows the polyline approximation of the edge                             |
| Direction    | Shows the edge segments directions                                       |

## Bounding box visualization

The Bounding Box Visualization feature represents the minimal box aligned with the cardinal axes that entirely encloses a geometric object. This feature enables users to:

- Understand the spatial extent of an object.
- Analyze the dimensions and proportions of the bounding box.
- Inspect how objects fit within the defined space constraints.

изображение

| Setting      | Description                                                                        |
|--------------|------------------------------------------------------------------------------------|
| Surface      | Shows the surface of the bounding box                                              |
| Transparency | Adjusts the transparency level of the bounding box surface                         |
| Edges        | Shows the edges of the bounding box, providing a clear outline                     |
| Axis         | Shows the axis vectors of the bounding box, indicating min and max points location |

Transform is applied to the BoundingBox when visualising it

## XYZ visualization

The XYZ Visualization feature illustrates the coordinates and orientation of points in the model space.
This feature enables users to:

- Visualize the position of points in the 3D space.
- Inspect the relationships between different coordinates in the model.

изображение

| Setting | Description                                                                                  |
|---------|----------------------------------------------------------------------------------------------|
| Planes  | Shows the coordinate planes for X, Y, and Z axes, helping to visualize spatial orientation   |
| Length  | Adjusts the length of the planes and axes, providing a better scale reference for the model. |
| X axis  | Shows the X axis direction and its alignment in the 3D space.                                |
| Y axis  | Shows the Y axis direction and its alignment in the 3D space.                                |
| Z axis  | Shows the Z axis direction and its alignment in the 3D space.                                |

Visualisation is not available for unit length vectors

## Color Picker editor

To fine-tune your chosen color, select the central color in the color bar. 
The fine-tuning control lets you change the color's HSV, RGB, and HEX values.

To choose a similar color, select one of the segments on the left and right edges of the color bar.

изображение

## Settings

Settings are saved between sessions. To completely reset to default values, open the settings and perform a reset

изображение

## Quality Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jeremytammik** [comment]
wow! brilliant!

**Comment by jeremytammik** [comment]
by the way, for 2D geometry like room boundaries etc., are you aware of my GeoSnoop utility? https://thebuildingcoder.typepad.com/blog/2014/04/determining-the-size-and-location-of-viewports-on-a-sheet.html

**Comment by Nice3point** [comment]
@jeremytammik thanks Jeremy for sharing the link, yes I have heard of it and seen it in some articles. In the current implementation I am using DirectContext3D to render 3d geometry, this will give a lot of possibilities to create independent geometry with many customisations

**Comment by jeremytammik** [comment]
wow, yes, absolutely, that will be ever so much more powerful.

**Comment by Nice3point** [comment]
The geometry rendering looks finished. It remains to write documentation and brush up all little details. Release is planned for this week

**Comment by jeremytammik** [comment]
In the XYZ visualisation, is there a way to distinguish between X, Y and Z axes?

**Comment by jeremytammik** [comment]
is thjere a way to control the length of the little vectors showing mesh triangle orientation? in the mesh, can one see the orientation of each triangle, i.e., the order of its three vertices (clockwise, anticlockwise)?

**Comment by jeremytammik** [comment]
this is brilliant work. it wil have a very significant positive impact on the usefulness of RevitLookup! thank you!

**Comment by jeremytammik** [comment]
> any other ideas how we can highlight them?

some coordinate system visualisations use three colours, e.g., RGB.

> do you suppose it would be useful?

only as little. when there are very many close together and they overlap a lot. low priority, though, IMHO.

**Comment by Nice3point** [comment]
Great suggestion about the colour.  Clockwise, anticlockwise direction we can just finalise in the next releases

**Comment by Nice3point** [comment]
Added documentation, Wiki section will be updated after release

**Comment by chuongmep** [comment]
I belive that visulize  by RGB is good idea, I did similar idea to visulize coordinate system before by color 👍
CoordinateSystem Display

**Comment by jeremytammik** [comment]
the description and images in your comment look good and clear, clearly explaining the purpose and us. i edited the first sentence, adding `analysis and understanding of the BIM`, and added 'aligned to cardinal axes' for bounding boxes. in `XYZ visualization`, i wonder whether one should add a note of `Transform` and or `coordinate system`. would they apply to the XYZ visualisation as well?

**Comment by Nice3point** [comment]
exactly, it is necessary to specify that we apply Transform to all BoundingBoxes. About XYZ, they are displayed as they are, according to their value. but visualisation of normal points with length 1 is disabled

**Comment by Nice3point** [comment]
@jeremytammik hi Jeremy, the release came out as early as last week, it's probably worth releasing a blog post as only 50 people have viewed it

**Comment by jeremytammik** [comment]
yes, i am aware. i have it high on my blogging list, both 2025.0.5 and 2025.0.6. i have to publish another post first, though, on special request from my superiors. maybe i can get in two posts this week.

**Comment by jeremytammik** [comment]
blog post is now live:  https://thebuildingcoder.typepad.com/blog/2024/06/revitlookup-geometry-visualisation.html

**Comment by Nice3point** [comment]
Awesome, that looks juicy 🎉

**Pull request merged**
