### PR TITLE
updated CI for Revit 2021

### PR DESCRIPTION
**Pull request by peterhirn**

### CODE REVIEW

**Comment by jeremytammik** [comment]
Thank you, looks good!

**Comment by jeremytammik** [comment]
The readme build flag currently says 'pipeline: failed'...

**Comment by peterhirn** [comment]
Hey Jeremy! The build now succeeded. Unfortunately I forgot to add the tag ` 2021.0.0.7`, can you add it?

**Comment by jeremytammik** [comment]
Yup, I see the green flag now. Thank you! Sure I will. Cheers!

**Pull request merged**
