### PR TITLE
Solution changes for multi-release building

### PR DESCRIPTION
**Pull request by harrymattison**
Create a signed MSI installer using Advanced Installer
Modify the Visual Studio solution to use macro variables to ease the process of building for different Revit version. All you need to do now is create a new configuration and the output direction, DLL references, and other items will automatically update

### CODE REVIEW

**Comment by jeremytammik** [comment]
hi harry, thank you for the enhancement! did you grab the latest version for 2021 before adding them? i see in your solution file mentions VS 15 whereas mine states VS 14... will that cause a problem for other developers using older versions of VS than you do, such as me?

**Comment by jeremytammik** [comment]
sign.bat uses your specific signature files... is this if use to others? can it be switched off if not signing? if i merge your pull request, will i be able to build myself at all, without signing?

**Comment by jeremytammik** [comment]
this all looks rather harry-specific and i worry whether i will be able to work with it at all myself... same for others, of course...

**Comment by harrymattison** [comment]
Hi Jeremy - I just pushed a new version built with Visual Studio 2015

**Comment by harrymattison** [comment]
That line is commented out with the REM statement. So it won't affect
anyone in its current state. I left it there as a guide for other people to
see a nice way to do the signing in a post-build event, but I am happy to
remove it if you'd like.

**Comment by harrymattison** [comment]
It is designed to be very generic and not at all specific to me or anyone
else. What looks problematic?

**Comment by jeremytammik** [comment]
great, i'll take your word for it then. i noticed the REM and then forgot about it again. thank you very much for your contribution! integrating and testing next.

**Comment by jeremytammik** [comment]
i integrated your changes, compiled, failed (no config defined), set the configuration to 2021, recompiled, and all works well. published as release https://github.com/jeremytammik/RevitLookup/releases/tag/2021.0.0.1. can you check that my steps described above dod not overwrite anything crucial for the multi-platform config? maybe now variables have been replaced by constants somewhere? thank you!

**Comment by jeremytammik** [comment]
would you like to update the notes on the multi-configuration stuff in the readme? there is already a section in there describing your installer for Revit 2020. it could be updated now for 2021... thank you!

**Comment by jeremytammik** [comment]
published to the blog: https://thebuildingcoder.typepad.com/blog/2020/04/revitlookup-2021-with-multi-release-support.html#4

**Pull request merged**
