### PR TITLE
Release 2024.0.8

### PR DESCRIPTION
**Pull request by Nice3point**
# Summary of the Pull Request

Changelog: https://github.com/jeremytammik/RevitLookup/blob/dev/Changelog.md 

## Quality Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jeremytammik** [comment]
yes. i see different settings from the ones you show above:

revitlookup_settings_pr

**Comment by Nice3point** [comment]
can you uncheck the squash and rebase checkboxes? it causes some difficulties when merging branches 🙈

**Comment by jeremytammik** [comment]
ok. done. i wish you a nice evening. must be rather late for you already? good night.

**Comment by Nice3point** [comment]
I'm going to bed in 2 hours, good night jeremy and have a good day)

**Pull request merged**
