### PR TITLE
Public snoop api

### PR DESCRIPTION
**Pull request by Nice3point**
# Summary of the Pull Request

Public API support
https://github.com/jeremytammik/RevitLookup/issues/171

**Description:** 

Usage:

```c#
var descriptors = DescriptorBuilder.Build(element);
var descriptors = DescriptorBuilder.Build(obj, document);
var descriptors = DescriptorBuilder.Build(typeof(ComponentManager));
```

## Quality Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jeremytammik** [comment]
cool! thank you! как вы думаете, александр? @CADBIMDeveloper

**Comment by CADBIMDeveloper** [comment]
@jeremytammik , ok, I was able to get descriptors in RPS, what's next?

**Comment by CADBIMDeveloper** [comment]
@Nice3point ,

Probably [here](https://github.com/jeremytammik/RevitLookup/blob/00231f653a967dc344da1dbe1e1a8582e8e5848c/RevitLookup/Core/Metadata/DescriptorBuilder.Api.cs#L48) should be BuildInstanceObject invocation

**Comment by Nice3point** [comment]
Oh, yes, i will fix it

**Pull request merged**
