### PR TITLE
Ignore `ActionEventHandler` when null - UI.Demo

### PR DESCRIPTION
**Pull request by ricaun**
# Summary of the Pull Request

When using `UI.Demo` the `Application.ActionEventHandler` is null.

The `EventMonitor.Subscribe` and `EventMonitor.Unsubscribe` throw exception.

## Quality Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by Nice3point — CHANGES_REQUESTED** [review]
A better solution would be to create a Mock viewmodel to create logic for the demo project that does not reference the Revit Api

изображение

**Comment by ricaun** [comment]
> A better solution would be to create a Mock viewmodel to create logic for the demo project that does not reference the Revit Api
> 

Yes. I'm not sure if this is right, the IEventsViewModel is something like this.
```C#
public interface IEventsViewModel : ISnoopViewModel
{
    void OnNavigatedTo();
    void OnNavigatedFrom();
}
```

**Comment by ricaun** [comment]
> > A better solution would be to create a Mock viewmodel to create logic for the demo project that does not reference the Revit Api
> 
> Yes. I'm not sure if this is right, the IEventsViewModel is something like this.
> 
> ```cs
> public interface IEventsViewModel : ISnoopViewModel
> {
>     void OnNavigatedTo();
>     void OnNavigatedFrom();
> }
> ```

Or this. 😀

```C#
public interface IEventsViewModel : INavigationAware, ISnoopViewModel {}
```

**Comment by Nice3point** [comment]
> Or this. 😀
> 
> ```cs
> public interface IEventsViewModel : INavigationAware, ISnoopViewModel 
> {
> }
> ```

or
 ```C#
public interface IEventsViewModel : INavigationAware, ISnoopViewModel;
```
in C# 12 you can use ; instead of {}
yeah, that's a great plan, let's do that)

**Comment by ricaun** [comment]
> ```cs
> IEventsViewModel 
> ```

Done! I added a Subscribe/Unsubscribe in the moq. Strange that all de RevitApi.dll is loaded when you go into the Events.

**Comment by Nice3point** [comment]
Awesome, thanks)

**Comment by Nice3point** [comment]
> Strange that all de RevitApi.dll is loaded when you go into the Events.

There because of using `using Autodesk.Revit.Exceptions;` in SnoopViewModelBase, I fixed it by inheriting ObservableObject instead of SnoopViewModelBase

**Pull request merged**
