### PR TITLE
Enhanced member support

### PR DESCRIPTION
**Pull request by Nice3point**
# Summary of the Pull Request

**Description:** 

Fields, events support
изображение

Private members support
изображение

Settings update 
изображение

## Quality Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Nice3point** [comment]
@jeremytammik  We need to discuss which options should be enabled by default

**Comment by Nice3point** [comment]
@jeremytammik in theory, we could do a release) and then do a survey

**Comment by jeremytammik** [comment]
That sounds like an effective approach to me. Then, I can mention on the blog to please take a look and respond within a given time frame, for example. How long? Or leave it open?

**Comment by Nice3point** [comment]
If you do a blog mention it's not obvious where users can vote) Let's maybe gather feedback on the new release and then release the poll on GitHub

**Comment by jeremytammik** [comment]
yes, better. then i'll just mention the new release and ask people to provide feedback on it.

**Pull request merged**
