### PR TITLE
Updating icon package

### PR DESCRIPTION
**Pull request by eirannejad**
Also added exception handling to https://github.com/jeremytammik/RevitLookup/commit/6de4f467081d9251ed7cccfb107a8574e52a20db

IMPORTANT: Credit https://icons8.com/ for the icons.

### CODE REVIEW

**Comment by jeremytammik** [comment]
hi ehsan, thank you very much for the update! regarding crediting icons8.com, do you think it will be enough to mention that in the repository readme? or where else would you suggest adding it?

**Comment by eirannejad** [comment]
Yes that's what I have done. Thry have a permissive license that needs link back. So a link at the credit section on the repo should be good I think.

**Comment by jeremytammik** [comment]
i added a mention at the end of the readme. do you think that is sufficient?

**Comment by eirannejad** [comment]
Yes. RevitLookup is an opensource project so the website says you'll get it for free. I think the credit link works.
https://icons8.com/license/

**Comment by jeremytammik** [comment]
mentioned here on the blog: http://thebuildingcoder.typepad.com/blog/2017/03/q4r4-tbc-import-and-revitlookup.html#8

**Comment by jeremytammik** [comment]
the compilation now generates three warning messages:

`C:\a\vs\RevitLookup\CS\Snoop\Forms\BindingMap.cs(93,18,93,37): warning CS0108: 'BindingMap.InitializeComponent()' hides inherited member 'ObjTreeBase.InitializeComponent()'. Use the new keyword if hiding was intended.
C:\a\vs\RevitLookup\CS\Snoop\Forms\Categories.cs(72,18,72,37): warning CS0108: 'Categories.InitializeComponent()' hides inherited member 'ObjTreeBase.InitializeComponent()'. Use the new keyword if hiding was intended.
C:\a\vs\RevitLookup\CS\Snoop\Forms\Geometry.cs(127,18,127,37): warning CS0108: 'Geometry.InitializeComponent()' hides inherited member 'ObjTreeBase.InitializeComponent()'. Use the new keyword if hiding was intended.
`

would you like to fix those so it compiles with zero warnings again?

thank you!

**Comment by jeremytammik** [comment]
please ignore my previous comment... i fixed those warning myself in release 2017.0.0.22.

**Comment by eirannejad** [comment]
Huh! I used the VS 2017 Community and didn't get any warnings! It compiled clean multiple times. That's odd.

**Comment by jeremytammik** [comment]
oh, cool. well, trivially fixed my end too now, so no problem. thank you very much for the icons! did you see alexander through your try-catch was excessive? it should indeed always be used as sparingly as possible.

**Comment by eirannejad** [comment]
Yes I just saw that. I saw something somewhere else that said the try catch is very expensive and should be used sparingly. I'll read about it more and try to fix as much as them as I can in the pyRevit code.

**Comment by jeremytammik** [comment]
http://thebuildingcoder.typepad.com/blog/2009/08/fixing-rvtmgddbg-for-mep-connectors.html
http://thebuildingcoder.typepad.com/blog/2017/02/revitlookup-using-reflection-for-cross-version-compatibility.html#12

**Pull request merged**
