### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Nice3point**
I'm not a native speaker, check the translation is correct

### CODE REVIEW

**Comment by jeremytammik** [comment]
On loading the project, Visual Studio displayed an error message and said, "Some of the properties associated with the solution could not be read."

**Comment by jeremytammik** [comment]
```
Rebuild started...
1>------ Rebuild All started: Project: RevitLookup, Configuration: Debug Any CPU ------
2>------ Skipped Rebuild All: Project: Installer, Configuration: Release Any CPU ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Rebuild All: Project: Build, Configuration: Debug Any CPU ------
3>Project not selected to build for this solution configuration 
1>RevitLookup -> Y:\a\src\rvt\RevitLookup\RevitLookup\bin\Debug\RevitLookup.dll
========== Rebuild All: 1 succeeded, 0 failed, 2 skipped ==========
```

**Comment by jeremytammik** [comment]
Installer config was set to release, the other two to debug. I switched all three to release. That produces an error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""Y:\a\src\rvt\RevitLookup\Installer\bin\Release\Installer.exe" "/MSBUILD:Installer" "/WIXBIN:" "/Configuration:Release" "/Platform:AnyCPU"" exited with code -532462766.	Installer	C:\Users\jta\.nuget\packages\wixsharp\1.18.1\build\WixSharp.targets	5	
```

Output:

```
Rebuild started...
1>------ Rebuild All started: Project: RevitLookup, Configuration: Release Any CPU ------
2>------ Rebuild All started: Project: Installer, Configuration: Release Any CPU ------
2>Installer -> Y:\a\src\rvt\RevitLookup\Installer\bin\Release\Installer.exe
2>Building MSI
2>
2>Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
2>   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
2>   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
2>   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
2>   at Installer.Installer.GetAssemblyVersion(String[] directories)
2>   at Installer.Installer.Main(String[] args)
1>RevitLookup -> Y:\a\src\rvt\RevitLookup\RevitLookup\bin\Release\RevitLookup.dll
3>------ Rebuild All started: Project: Build, Configuration: Release Any CPU ------
2>C:\Users\jta\.nuget\packages\wixsharp\1.18.1\build\WixSharp.targets(5,5): error MSB3073: The command ""Y:\a\src\rvt\RevitLookup\Installer\bin\Release\Installer.exe" "/MSBUILD:Installer" "/WIXBIN:" "/Configuration:Release" "/Platform:AnyCPU"" exited with code -532462766.
2>Done building project "Installer.csproj" -- FAILED.
3>Build -> Y:\a\src\rvt\RevitLookup\Build\bin\Release\Build.dll
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========
```

**Comment by jeremytammik** [comment]
How should the VS > Build > Configuration Manager be set up to rebuild all successfully?

**Comment by jeremytammik** [comment]
The Installer project cannot be set to Debug, only Release. The other two work fine with Debug.

**Comment by jeremytammik** [comment]
It looks great! Thank you very much for the readme update. Your English looks perfect to me.

**Comment by Nice3point** [comment]
I don't have VisualStudio but try this: install Nuke global tools, run `dotnet tool install Nuke.GlobalTool --global` in terminal. then. Run `nuke` command once in terminal. Then try running debug

**Comment by Nice3point** [comment]
изображение
The build and Installer project builds must be disabled for the Debug / release configuration

**Comment by Nice3point** [comment]
This error is caused by the installer project, it should not build for the debug version

**Comment by Nice3point** [comment]
изображение
If Visual Studio builds even disabled projects, try deleting all the config with the Build and Installer project in the .sln file

**Comment by Nice3point** [comment]
https://www.youtube.com/watch?v=1ukfS_ryI5M  Watch the video, Debug on my computer, at the end I showed how to remove configurations from the solution

**Comment by Nice3point** [comment]
https://github.com/jeremytammik/RevitLookup/commit/52d5adef72e699fb3112c047bed98cec7fe0df57#diff-ef4019d5ca3f72d12ff55f033c95c78fcb96d183aa6863fa65393fac5d6a8a3aR30 You added the assembly of the Installer project in the last commit, you do not need to do this, this is the problem of the error, remove these two added lines and everything should work

**Comment by Nice3point** [comment]
I added the disabled configurations so as not to disturb the error from Msbuild about the lack of configuration, you can ignore the disabled configurations

**Comment by Nice3point** [comment]
Please rollback your last commit and share the result

**Comment by Nice3point** [comment]
> On loading the project, Visual Studio displayed an error message and said, "Some of the properties associated with the solution could not be read."

https://github.com/jeremytammik/RevitLookup/blob/master/RevitLookup.sln#L39-L44 I have no such error, try deleting these lines, they appeared in one of your commits =)

**Comment by Nice3point** [comment]
did I correctly write in the readme that the project has a startup configuration for Visual Studio? is this the file that starts Revit after building the project? https://github.com/jeremytammik/RevitLookup/blob/master/RevitLookup/Properties/launchSettings.json

**Comment by jeremytammik** [comment]
i reverted the build config changes and it seems to compile and debug correctly now. sorry for messing things up. i am now well versed in github usage, so even rolling back my last commit is a challenge. i set up the `dev` branch but am not well versed in juggling multiple branches either.

regarding the Revit setup to access all the samples: i make use of RvtSamples from the Revit SDK to load all external commands. The RvtSamples addin reads a file names `RvtSamples.txt` listing all the Revit SDK samples and loads those. At the end of the text file, I include two further text files. The original implementation was described in [Loading The Building Coder Samples](https://thebuildingcoder.typepad.com/blog/2008/11/loading-the-building-coder-samples.html) in 2008. It is still in place. I find that the most efficient way to load hundreds of external commands and maintain them across multiple versions of Revit, without having to implement separate `addin` files for each.

**Comment by jeremytammik** [comment]
i tried running `nuke` as described. You say, run it in the 'terminal of your IDE'. My IDE is Visual Studio. It does not recognise nuke. Not does the Windows or VS external terminal:

```
*********************************************************************
** Visual Studio 2019 Developer PowerShell v16.9.4
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
PS C:\Users\jta\source\repos> y:
PS Y:\> cd Y:\a\src\rvt\RevitLookup
PS Y:\a\src\rvt\RevitLookup> nuke
nuke : The term 'nuke' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ nuke
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (nuke:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Do I need to install something separate?

**Comment by jeremytammik** [comment]
Ah, found it, I think: https://nuke.build/docs/getting-started/setup.html

**Comment by jeremytammik** [comment]
I ran nuke successfully, then started Revit.exe in the VS debugger. That produced the warning saying that I was attempting t debug a release version of RevitLookup. I never wanted a release version. How can I ensure that I have a debug version to debug? The build con fig is set up just as in your image above.

**Comment by jeremytammik** [comment]
I added you as a contributor.

**Comment by Nice3point** [comment]
Download the video from the link. The first is about Build. The second is about merging branches. https://dropmefiles.com/dNdfC The main point of the dev branch is this:
- Developers commit their changes to the dev branch. They create a pull request, you test, maybe make your own edits, then merge with the master branch, and the user will see these changes, the installer will also generate for the master branch, as well as creating a new release on GutHub. Dev branch is only for people like me who want to make their own improvements to the project. Watch this video on the importance of branches https://www.youtube.com/watch?v=gW6dFpTMk8s

**Comment by Nice3point** [comment]
in the dev branch, the build of the Installer and Release configuration for Debug was included. Maybe this was the problem, if not, open screenshots or videos of your problem so that I understand the situation

**Comment by Nice3point** [comment]
I'll update the Readme later

**Comment by Nice3point** [comment]
I wrote about the importance of the configured configuration here https://github.com/Nice3point/RevitTemplates/wiki/Project-creation Link is in Reame

**Comment by Nice3point** [comment]
Change the version number only in the master branch. I forgot to say, since the installer now contains all versions, you don't need to update the GUID, you don't have to go into the installer project now, it is configured to work correctly.

**Comment by Nice3point** [comment]
I have pushed a commit to the dev branch, try to merge it with the master branch. To do this, while in the master branch, right-click on the dev branch in VisualStudio and select "Merge selected into current", perhaps it will be called a little differently. Then push the commit with the merge.

**Comment by jeremytammik** [comment]
> is this the file that starts Revit after building the project?

I assume so. I only set up the debug settings n VS; apparently, it then generated that file.

**Comment by Nice3point** [comment]
> 
> 
> > is this the file that starts Revit after building the project?
> 
> I assume so. I only set up the debug settings n VS; apparently, it then generated that file.

I installed VisualStudio 2019, I have no errors when building and opening the project. The only problem is that this file is specified in the startup configuration. Other users of this file, and even the disk may not have, this will cause an error when opening the revit.
изображение


Regarding working with branches, in VisualStudio they are located at the bottom right, while in the master branch, right-click on the dev branch and select merge to transfer all changes.
изображение

**Comment by Nice3point** [comment]
At this point, I have merged all the changes. Also updated the background of the installer with the name of this project.

**Comment by jeremytammik** [comment]
super cool. thank you very much!

I would like to conclude this update asap and publish on the blog. for that, i first need to explore the git stuff with the dev branch.  

i use command line github in the Mac terminal. i do not believe that my VS is aware of the git context. i can try it out. maybe it will work. however, i would actually prefer just using the git command line tools.

**Comment by Nice3point** [comment]
if you sent commits from Visual Studio, then there should be no problems with working with branches. To explore, try in the dev branch to make any changes, merge with the master branch and push to the remote repository.

**Comment by jeremytammik** [comment]
okey-doke, i'll try it out.

**Comment by jeremytammik** [comment]
my VS does not work with git. i used the Mac terminal git to switch branches, pull, push, commit and merge.

**Comment by jeremytammik** [comment]
i still do not know how to install the new DLL out of the box. I ran successfully executed `nuke` and then executed `output\RevitLookup-22.0.2.2.msi`. The latter failed with an error message saying that the roaming add-ins folder for 2019 could not be created. all i want to do is compile, run and debug RevitLookup with Revit 2022. i don't really want or need the installer. is there any way to just automatically copy the current DLL to the Revit 2022 add-ins folder every time it is recompiled?

**Comment by jeremytammik** [comment]
I still get the message saying 

[Window Title]
Just My Code Warning

[Main Instruction]
You are debugging a Release build of RevitLookup.dll. Using Just My Code with Release builds using compiler optimizations results in a degraded debugging experience (e.g. breakpoints will not be hit).

[Stop Debugging] [Disable Just My Code and Continue] [Continue Debugging] [Continue Debugging (Don't Ask Again)]

**Comment by Nice3point** [comment]
DLL is copied to the output folder automatically, now I will record a video, I have no warnings even in VisualStudio, do you have Debug configuration enabled here?
изображение

**Comment by Nice3point** [comment]
@jeremytammik https://dropmefiles.com/ZzEye. video here. I cloned the project, made sure the Debug configuration was set, hit the start button, the program stopped at a breakpoint. There are no problems.

**Comment by Nice3point** [comment]
Are you trying to debug the **Release** configuration?

**Comment by jeremytammik** [comment]
i;m trying not to debug the release version. i think i got it sorted now. sorry again for all the confusion.

**Comment by Nice3point** [comment]
now you have no errors or warnings?

**Comment by jeremytammik** [comment]
correct. no errors, no warnings, and i debugged the current release. i'll commit and create the new release now, then document what we have been up to. i can't really explain everything, so I don't yet quite know what I am going to say at all...

**Comment by Nice3point** [comment]
you don't need to run **nuke** to debug. Only the green arrow on the VisualStudio panel. Nuke is used only for the purpose of building a project, it simplifies building if, for example, the project has several configurations, for example, for the 20th, 21st and 22nd versions of revit, Nuke build all dll variants at once. The build system is only needed to release a product.

**Comment by Nice3point** [comment]
It's okay if there is a misunderstanding, the Installer project has emerged from new projects, which allows you to create an installer. The Build project, which contains the Nuke system. It allows you to automate the build of the project, allows you to build the installer after the build of the project, and makes it possible to do it all at once on GitHub in the cloud.

**Comment by jeremytammik** [comment]
it seems to me that i can now just recompile the project with `build all` and that automatically installs the current build in the Revit `Add-Ins` folder, which is exactly what i want.

**Comment by jeremytammik** [comment]
https://github.com/jeremytammik/RevitLookup/releases/tag/2022.0.2.2

**Comment by Nice3point** [comment]
Also, the project was refactored taking into account the latest versions of the c # language. Some places have been optimized, for the ribbon I created extension methods that are from
 `optionsBtn.AddPushButton (new PushButtonData (" HelloWorld "," Hello World ... ", ExecutingAssemblyPath, typeof (HelloWorld) .FullName));`
 write like this 
`optionsBtn.AddPushButton (typeof (HelloWorld)," HelloWorld "," Hello World ... ");`

MApp.DocumentClosed += m_app_DocumentClosed;

The latest versions of the C # language allow you to write like this:
`MApp.DocumentClosed += m_app_DocumentClosed;`
instead of
`m_app.DocumentClosed += new EventHandler<Autodesk.Revit.DB.Events.DocumentClosedEventArgs>(m_app_DocumentClosed);`

**Comment by Nice3point** [comment]
> 
> 
> https://github.com/jeremytammik/RevitLookup/releases/tag/2022.0.2.2

I see you managed to merge the branches)

**Comment by jeremytammik** [comment]
i think i used `$ git merge dev` :-)

**Comment by Nice3point** [comment]
I slightly updated the Build section in the Readme so that there are no misunderstandings and thoughts that you need to run nuke to debug. Now these are 2 independent blocks

**Comment by jeremytammik** [comment]
taking a look...

**Comment by Nice3point** [comment]
I have already updated 2 branches)

**Comment by Nice3point** [comment]
You don't have to switch to the dev branch to update auxiliary files like Readme. Dev branch is only for code related to plugin operation or Nuke system. Readme file that does nothing, so changes can be made directly to the master branch)

**Pull request merged**
