### PR TITLE
Upgraded csproj file to dotnet core and CI to Revit 2022

### PR DESCRIPTION
**Pull request by peterhirn**
- Upgraded csproj file to dotnet core
- Removed Revit version specific build configurations
- Upgraded CI to Revit 2022

New csproj does not contain the previous PostBuild step which copied the assembly to the Revit Add-in directory. If you want this back in I can update this PR.

Generally it would be nice if we could find a better way to handle the Revit API assemblies, options:
- add them to this repository
- use a third-party nuget package (eg. https://www.nuget.org/packages/Autodesk.Revit.SDK/)
- create a new nuget package

~~Edit: I just realized the addin icon is missing, marked this PR as Draft~~
Edit: Fixed missing ribbon icon

### CODE REVIEW

**Comment by jeremytammik** [comment]
I like the idea of using a NuGet package. 

Who is the owner of Autodesk.Revit.SDK? I don't know. I can contact the owners and ask, unless you know.

Alternatively, I can probably gain personal access to https://www.nuget.org/packages/Autodesk.Forge/ if I ask sweetly enough, and promise to use it for the Revit API assemblies and nothing else.

**Comment by peterhirn** [comment]
I just discovered the Autodesk.Revit.SDK nuget package, never used it but it looks fine. Owner is Zhmayev Yaroslav (see info panel to the right https://www.nuget.org/packages/Autodesk.Revit.SDK/). The package looks very official, maybe Zhmayev is a Autodesk employee?

Creating and pushing a new nuget package is super simple using `dotnet pack` / `dotnet nuget push`, see https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli, but requires a nuget.org API key.

I don't think you should use the Forge nuget.org account, seems like a potential security risk.

Most of the work is probably figuring out good names/versions for the packages, creating repositories on github to host the assemblies, (optional) add a CI to build and push the packages and supporting the packages with updates in the future.

**Comment by jeremytammik** [comment]
I contacted the package owner Salaros: https://www.nuget.org/packages/Autodesk.Revit.SDK/2022.0.0.2001/ContactOwners

I also created an own NuGet account: https://www.nuget.org/profiles/jeremytammik

I also asked about access to the Autodesk.Forge package.

And for advice from my colleagues on which they think is best.

So I'm ready to go either way.

**Comment by jeremytammik** [comment]
When you say, creating repositories on github to host the assemblies, do you mean grab the precompiled assemblies from Revit.exe and just copy them to GitHub? That we can do and should be easy.

**Comment by jeremytammik** [comment]
You removed the draft status. Does that mean I can merge this now?

**Comment by peterhirn** [comment]
Regarding adding assemblies: yes that's what I meant. It would be even easier to just add the two required assemblies (RevitAPI.dll / RevitAPIUI.dll) to this repository (enable LFS for *.dll in `.gitattributes` first, if github supports that).

Regarding draft status: yes, icon is now displayed, everything should work, although I only did some very limited testing.

**Comment by jeremytammik** [comment]
actually, it is more than those two; more like five or six, including API, UIAPI, Macros, UIMacros, IFC, AdWindows. more or less.

**Comment by jeremytammik** [comment]
ok, well, then i'll merge now to clear this and have it updated before people start downloading...

**Comment by peterhirn** [comment]
This PR removes the other (unused) Revit assemblies.

**Comment by jeremytammik** [comment]
make sense. thank you very much for cleaning up!

**Comment by jeremytammik** [comment]
i cannot load the project into visual studio. i guess my version is too old now. i would orefer to use as old as possible. do you have any idea what i can do to load it into VS 2017 version 15.9.14?

**Comment by peterhirn** [comment]
Sorry, it seems VS 2017 does not support dotnet core >= 3, https://stackoverflow.com/questions/53641740/use-visual-studio-2017-with-net-core-sdk-3-0/55629622.

If you want to you can just revert the PR and I will update it to only include the changes to fix the CI.

**Comment by jeremytammik** [comment]
okey-doke, let's do that then, please. sorry for the bother.

**Comment by jeremytammik** [comment]
maybe i should upgrade vs, but maybe not now suddenly in a rush and under pressure.

**Comment by jeremytammik** [comment]
i copied back the previous `*.sln` and `*.csproj` and all is fine now.

**Comment by jeremytammik** [comment]
so no need to revert the PR.

**Comment by michaldengusiak** [comment]
yes this would be super cool @jeremytammik  if you have VS2019 so  we could support dotnet core

**Comment by jeremytammik** [comment]
ok. the new CI setup is in release 2022.0.0.1. 

I'll see about upgrading VS to 2019 asap.

oops, already created the release before i saw your note about a new `yml`.

**Comment by jeremytammik** [comment]
will you create a new PR for the new .gitlab-ci.yml?

**Comment by peterhirn** [comment]
Yes, or I can just post the diff, what do you prefer?

**Comment by jeremytammik** [comment]
new PR. :-)

**Pull request merged**
