### PR TITLE
Pushed the missed files

### PR DESCRIPTION
**Pull request by chekalin-v**

### CODE REVIEW

**Comment by jeremytammik** [comment]
hi victor, i integrated and tested. i snooped the DB, went to materials, and see Air 418 as the first entry. from there, i go to AppearanceAssetId > Clear - Light > GetRenderingAsset > GenericSchema > Item > AssetPropertyDoubleArray4d > common_Tint_color > GetValueAsDoubles. i see four double entries listed, but none of them has a value. in fact, all four of them display no properties at all. is that expected? can you please share exact step-by-step instructions how to test and verify the functionality of your enhancement? thank you!

**Comment by jeremytammik** [comment]
https://thebuildingcoder.typepad.com/blog/2019/03/-architecture-edit-and-continue-snooping-appearance-assets.html#4

**Comment by chekalin-v** [comment]
Hi Jeremy, I am busy a little bit to write the detailed instruction why and what I did. But fixed the GetValueAsDoubles string value in the new Pull Request

**Comment by jeremytammik** [comment]
hi victor, no problem! i am sure all interested developers will understand by themselves from your pictures. so all is well in the release i published? yes? thank you!

**Comment by jeremytammik** [comment]
oh no, i see now, your new pull request. ok, i'll integrate that and fix the blog post right away.

**Comment by chekalin-v** [comment]
I needed these changes to view property values as well

**Comment by jeremytammik** [comment]
i added pull request #50 to the blog post and made a new release. is all ok now? can ii stop? thx!

**Comment by chekalin-v** [comment]
fine with me. So far I am not planning to do more changes. The functionality I've added is enough for me.

**Pull request merged**
