### PR TITLE
Update Value Width

### PR DESCRIPTION
**Pull request by ricaun**
Update the Width of the `Value` ListView to fit better.

Revit Lookup - Application PR

### CODE REVIEW

**Comment by jeremytammik** [comment]
Thank you for the enhancement. It does not work in all the windows, it seems, cf. attached image produced by snooping wall > geometry > elements...
snoop_element_geometry

**Comment by jeremytammik** [comment]
presumably, a better approach would be to query the total window width and adjust the `Value` column to gobble all the space remaining after the tree view and the field column have grabbed their share...

**Comment by ricaun** [comment]
This on the `Utils.DataItemSelected` and `Utils.Display` works better.
```C#
private static void UpdateLastColumWidth(ListView lvCur)
{
    lvCur.Columns[lvCur.Columns.Count - 1].Width = -2;
}
```
I don't know if has a better place to add the code.

**Comment by jeremytammik** [comment]
sounds good... did you test? would you like to submit a new pull request for that? thank you!

**Comment by ricaun** [comment]
I gonna test and submit a new PR.

**Pull request merged**
