### PR TITLE
Deprecation update

### PR DESCRIPTION
**Pull request by WspDev**
Fixed deprecation warning in FamilyTypeParameterValuesStream.

### CODE REVIEW

**Comment by jeremytammik** [comment]
thank you very much for catching this!

**Comment by WspDev** [comment]
It's the least I could do.
I was going to attempt to upgrade it to 2022 and realised it already had been. :)

**Comment by jeremytammik** [comment]
that was nice of you! yes, it is important enough nowadays to earn high priority and quick treatment...

**Comment by jeremytammik** [comment]
integrated in https://github.com/jeremytammik/RevitLookup/releases/tag/2022.0.0.8

**Pull request merged**
