### PR TITLE
Update RevitVersion

### PR DESCRIPTION
**Pull request by Nice3point**
# Summary of the Pull Request

**Description:** 

Revit 2023 support

## TODO

- [ ] Update libraries
- [x] Update Readme
- [x] Update code header
- [ ] Wait for the release of the stable version of Revit

### CODE REVIEW

**Comment by Nice3point** [comment]
@jeremytammik I did not find deprecated methods, I think it is possible to support both the 22nd and 23rd version at the same time, what do you think?

**Comment by Nice3point** [comment]
Also I would switch to a 3 number version number like 2023.0.0 instead of 2023.0.0.0

**Comment by Nice3point** [comment]
@jeremytammik I don’t want to release a new version yet, just update the code that has nothing to do with the new API, if I break the rules somewhere, write about it, if anything, we will delete the branch and PR

**Comment by jeremytammik** [comment]
great! thank you!

**Comment by jeremytammik** [comment]
Yipee! New record! Never been so fast before!

**Pull request merged**
